# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fNEK6Bn4y8ec5tyehTOtzPYWF3fSyDKc

# **Calculating NPS(Net Promoter Score) in a Survey.**
"""

import numpy as np
survey = np.loadtxt('/content/survey.txt')
survey.shape[0]

"""# 1.Filter scores where respondents are detractors (scores <= 6)."""

detractors = survey[survey <= 6]
detractors.shape[0]

"""# 2.Find promoter percentage. (score >=9)"""

promoters = survey[survey >= 9]
100*promoters.shape[0]/survey.shape[0]

"""# 3: What does this line of code calculate?
**NPS** = percentage_promoters - percentage_detractors

A. Number of respondents who are promoters.

B. Total percentage of neutral respondents.

C. Net Promoter Score (NPS).

D. Percentage of detractors only.
"""

100*(promoters.shape[0] - detractors.shape[0])/survey.shape[0]

"""# **KPI Summary**"""

total = len(survey)
promoters = survey[survey >= 9]
passives = survey[(survey > 6) & (survey < 9)]
detractors = survey[survey <= 6]

promoter_pct = len(promoters)/total*100
passive_pct = len(passives)/total*100
detractor_pct = len(detractors)/total*100

nps = promoter_pct - detractor_pct

print("Total Responses :", total)
print("Promoter %      :", round(promoter_pct,2))
print("Passive %       :", round(passive_pct,2))
print("Detractor %     :", round(detractor_pct,2))
print("NPS Score       :", round(nps,2))

"""# **Rating Distribution Histogram**"""

import matplotlib.pyplot as plt

plt.figure(figsize=(8,5))

plt.hist(survey, bins=11)

plt.title("Rating Distribution")
plt.xlabel("Rating")
plt.ylabel("Number of Responses")

plt.show()

"""# **Promoter vs Passive vs Detractor Bar Chart**"""

total = len(survey)
promoters = np.sum(survey >= 9)
passives = np.sum((survey >= 7) & (survey <= 8))
detractors = np.sum(survey <= 6)

print(f"Total Responses: {total}")
print(f"Promoters: {promoters}")
print(f"Passives: {passives}")
print(f"Detractors: {detractors}")

labels = ['Promoters', 'Passives', 'Detractors']
counts = [promoters, passives, detractors]

plt.figure(figsize=(8,5))

plt.bar(labels, counts)

plt.title("NPS Categories")
plt.ylabel("Number of Customers")

plt.show()

"""# **Pie Chart**"""

labels = ['Promoters', 'Passives', 'Detractors']
sizes = [promoters, passives, detractors]

plt.figure(figsize=(7,7))

plt.pie(
    sizes,
    labels=labels,
    autopct='%1.1f%%'
)

plt.title("Customer Segmentation by NPS")

plt.show()

"""# **Project Insights**

• Analyzed 1,167 customer survey responses.

• Calculated Net Promoter Score (NPS) of 23.74.

• Identified 52.19% Promoters, 19.37% Passives, and 28.45% Detractors.

• Performed customer sentiment segmentation using Python and Pandas.

• Generated actionable business insights from survey ratings.
"""